"api_base": {
  "GPT": "https://vip.DMXapi.com/v1",
  "VLM": "https://vip.DMXapi.com/v1",
  #  "VLM": "https://xiaoai.plus/v1",

  #      "GPT": "https://xiaoai.plus/v1",
  "QWEN": "https://dashscope.aliyuncs.com/compatible-mode/v1",
}
"api_key": {
  #      "GPT": "sk-5mU8poYeiI4bydH492B59125206344598312600438205f65",
  #    "GPT": "sk-tT8XYVZUo5PZZsg1ppMNHOcJt0hZL59HSxI8B79VQSw6Wh7t",
  "GPT": "sk-JVDiyrvh5BRPinBhEU40yYia87BdQVKrwDqH7PDRYERSL8rK",

  "VLM": "sk-JVDiyrvh5BRPinBhEU40yYia87BdQVKrwDqH7PDRYERSL8rK",
  #  "VLM": "sk-5mU8poYeiI4bydH492B59125206344598312600438205f65",

  "QWEN": "sk-99f55920b8834f6f8c1e78f8d3691c26",
  "CLAUDE": "input your claude api here"
}
"model": {
  "VLM": "gpt-4o",
  "GPT": "gpt-4o",
  #  "GPT": "o1-preview",
  "QWEN": "qwen-vl-plus",
  "CLAUDE": "input the claude model here"
}
